version: '3'

services:
  barker:
    build: .
    ports:
    - 1337:1337
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: barker
      MYSQL_USER: barker
      MYSQL_PASSWORD: barker
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
